version: "3.8"

services:
  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - DATABASE_URL=postgresql+asyncpg://admin:P455w0rd@db:5432
     - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    volumes:
      - "./app:/home/app"
      - "./scripts:/home/scripts"
    ports:
      - "8000:8000"
    command: poetry run scripts/run.sh --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m


  db:
    image: postgres:14.4
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=P455w0rd
    ports:
      - "5432:5432"
    volumes:
      - "./data/db:/var/lib/postgresql/data"

  pg-admin:
    image: dpage/pgadmin4
    restart: unless-stopped
    shm_size: '256mb'
    ports:
      - "5556:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=alessio.izzo@miller.com
      - PGADMIN_DEFAULT_PASSWORD=password


