version: "3.8"

services:
  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./app:/home/app"
      - "./scripts:/home/scripts"
    ports:
      - "8000:8000"
    command: poetry run scripts/run.sh --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
