FROM node:18 as build

WORKDIR /app

COPY ./frontend/package.json ./frontend/yarn.lock ./
RUN yarn install 

COPY frontend .

RUN yarn build

RUN ls build

# Bundle static assets with nginx
FROM nginx:1.21.0-alpine as production
# Copy built assets from `builder` image
COPY --from=build /app/build/ /var/www/

RUN ls  /var/www
# Add your nginx.conf
COPY nginx.docker.conf /etc/nginx/conf.d/default.conf
# Expose port
EXPOSE 80
# Start nginx
CMD ["nginx", "-g", "daemon off;"]
